### ISSUE TITLE
How is this supposed to be used?

### ISSUE THREAD

**Issue by lethjakman** [thiagoarrais/hdbc-oracle#1]
Hello, this looks like it can solve my problem. However, I'm not sure how to use your driver. Is there any chance we could get a quick README or something?

**Comment by thiagoarrais** [comment]
That would be a very nice idea seven or eight years (!) ago, unfortunately... Now even I don't know what this thing is supposed to do. Maybe it won't even work with newer Haskell/HDBC versions...

If you're still interested, I would advise you to take a look at the other HDBC drivers. I probably just ported their concept to oracle at the time...

P.S.: Sorry for the delay... Haven't been checking my github profile in a while...

**Comment by lethjakman** [comment]
That's fine, thank you for the help!
